version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLIC_KEY=${CLERK_PUBLIC_KEY}
      - CLERK_FRONTEND_API_URL=${CLERK_FRONTEND_API_URL}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
