version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: postgresql://postgres:DfsWbOwGHJLLveifLbUDnWyloOtmfRmU@autorack.proxy.rlwy.net:48766/railway
      NODE_ENV: development
      PORT: ${PORT}
      HOST: '0.0.0.0'
    volumes:
      - ./src:/app/src
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${PORT}/api/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
