[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
TZ = "UTC"
DATABASE_URL = "postgresql://postgres:postgres@unicas-nest-backend.railway.internal:5432/railway"
JWT_SECRET = "your-super-secret-key-change-this-in-production"
FRONTEND_URL = "http://localhost:3001"
