@baseUrl = http://localhost:3000/api

### Step 1: Login with admin credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "phone": "912345678",
    "password": "123123"
}


### Store the auth token from login response
@authToken = {{login.response.body.access_token}}

### Get all juntas
GET {{baseUrl}}/juntas
Authorization: Bearer {{authToken}}

### Get all members of a junta
GET {{baseUrl}}/members/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

### Store the junta ID from create response
@juntaId = 3b7beb91-9844-4a10-84b1-3055c5643aa8

### Store the member ID from create response
@memberId = 64b0d2d8-b0fd-4d53-89a7-b76c21ded612

#### LOAN TYPES:
# 'CUOTA_REBATIR' | 'CUOTA_FIJA' | 'CUOTA_VENCIMIENTO' | 'CUOTA_VARIABLE'
#### PAYMENT TYPES:
# 'MENSUAL' | 'QUINCENAL' | 'SEMANAL';
#### GUARANTEE TYPES:
# 'AVAL' | 'INMUEBLE' | 'HIPOTECARIA' | 'PRENDARIA';

### Step 7: Create a personal prestamo
# @name createPersonalPrestamo
POST {{baseUrl}}/prestamos
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "juntaId": "{{juntaId}}",
    "memberId": "{{memberId}}",
    "request_date": "2024-11-01",
    "amount": "12",
    "monthly_interest": "2",
    "number_of_installments": 6,
    "loan_type": "CUOTA_REBATIR",
    "reason": "Personal expenses",
    "guarantee_type": "INMUEBLE",
    "guarantee_detail": "Personal guarantee",
    "form_purchased": true,
    "payment_type": "MENSUAL"
}

### Check all prestamos
GET {{baseUrl}}/prestamos/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

@newPrestamoId = bffefe7f-b20a-463a-b415-2193ec49ca87

### Get loan schedule
GET {{baseUrl}}/prestamos/{{newPrestamoId}}/remaining-payments
Authorization: Bearer {{authToken}}

### Step 9: Add a pago (loan payment)
# @name createPago
POST {{baseUrl}}/prestamos/{{newPrestamoId}}/pagos
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "amount": 7
}

### Get all pagos
GET {{baseUrl}}/prestamos/junta/{{juntaId}}/pagos
Authorization: Bearer {{authToken}}




### Create Agenda
POST {{baseUrl}}/agenda
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "juntaId": "3b7beb91-9844-4a10-84b1-3055c5643aa8",
    "title": "Asamblea 2",
    "description": "Reunión ordinaria",
    "date": "2024-11-18T15:00:00.000Z"
}

###
@agendaItemId = "645c2d66-1c6f-4205-8976-aca69012abbe"


#### Get Attendance
GET {{baseUrl}}/attendance/list?juntaId={{juntaId}}&startDate=2024-11-18&endDate=2024-11-24
Authorization: Bearer {{authToken}}


### Attendance Mark
# @name attendanceMark
POST {{baseUrl}}/attendance/mark
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "memberId": "5edd164b-caf7-49eb-a0c4-547d2bdbfc02",
    "agendaItemId": "645c2d66-1c6f-4205-8976-aca69012abbe",
    "asistio": true
}



### Get all agenda items for a junta
GET {{baseUrl}}/agenda/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

### Create Attendance schedule
# @name attendanceSchedule
POST {{baseUrl}}/schedule
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "juntaId": "3b7beb91-9844-4a10-84b1-3055c5643aa8",
    "name": "Weekly Member Meeting",
    "frequency": "WEEKLY",
    "startDate": "2024-11-18T00:00:00Z",
    "weeklySchedules": [
    {
      "dayOfWeek": 1,
      "startTime": "2024-11-18T15:00:00Z"
    }
  ]
}


### Get all schedules
GET {{baseUrl}}/schedule/junta/{{juntaId}}
Authorization: Bearer {{authToken}}



###  Generate Agenda Items
POST {{baseUrl}}/schedule
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "juntaId": "{{juntaId}}",
    "name": "Weekly Member Meetings",
    "frequency": "WEEKLY",
    "startDate": "2024-11-18T00:00:00Z",
    "weeklySchedules": [
        {
            "dayOfWeek": 1,
            "startTime": "2024-11-18T15:00:00Z"
        },
        {
            "dayOfWeek": 2,
            "startTime": "2024-11-19T15:00:00Z"
        },
                {
            "dayOfWeek": 3,
            "startTime": "2024-11-20T15:00:00Z"
        },
                {
            "dayOfWeek": 4,
            "startTime": "2024-11-21T15:00:00Z"
        },
                {
            "dayOfWeek": 5,
            "startTime": "2024-11-22T15:00:00Z"
        },
                {
            "dayOfWeek": 6,
            "startTime": "2024-11-23T15:00:00Z"
        },
                {
            "dayOfWeek": 7,
            "startTime": "2024-11-24T15:00:00Z"
        }

    ]
}

###
@schedule_id = "7f2282ce-6253-4018-9e80-8563156427da"

### Generate agenda items for a date range:
# @name attendanceScheduleGenerate
POST {{baseUrl}}/schedule/{{schedule_id}}/generate
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "startDate": "2024-11-18T00:00:00Z",
    "endDate": "2024-11-24T00:00:00Z"
}

### Debug Schedule
GET {{baseUrl}}/schedule/debug/all
Authorization: Bearer {{authToken}}

### Get Schedule
GET {{baseUrl}}/schedule/{{schedule_id}}
Authorization: Bearer {{authToken}}

# ###
# @schedule_id = "745887db-f1d8-4f3b-a806-be5edddf8677"

### Delete Schedule
DELETE {{baseUrl}}/schedule/{{schedule_id}}
Authorization: Bearer {{authToken}}

### Get Schedule using a date range
GET {{baseUrl}}/schedule/junta/{{juntaId}}/range?startDate=2024-11-18&endDate=2024-11-24
Authorization: Bearer {{authToken}}


# @schedule_id = "745887db-f1d8-4f3b-a806-be5edddf8677"
####
POST {{baseUrl}}/schedule/{{schedule_id}}/generate
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "startDate": "2024-11-18T00:00:00.000Z",
    "endDate": "2024-11-24T23:59:59.999Z"
}

####
GET {{baseUrl}}/schedule/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

@prestamoId = 'da6c42e4-d2b6-4b54-8937-d77e61d2fb63'
###
GET {{baseUrl}}/prestamos/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/prestamos/{{prestamoId}}/remaining-payments
Authorization: Bearer {{authToken}}