@baseUrl = http://localhost:3000/api

### Step 1: Login with admin credentials
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "phone": "912345678",
    "password": "123123"
}


### Store the auth token from login response
@authToken = {{login.response.body.access_token}}


### Get all juntas
GET {{baseUrl}}/juntas
Authorization: Bearer {{authToken}}

### Get all members of a junta
GET {{baseUrl}}/members/junta/{{juntaId}}
Authorization: Bearer {{authToken}}

### Store the junta ID from create response
@juntaId = 3b7beb91-9844-4a10-84b1-3055c5643aa8

### Store the member ID from create response
@memberId = 64b0d2d8-b0fd-4d53-89a7-b76c21ded612


### Create Agenda
POST {{baseUrl}}/agenda
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "juntaId": "3b7beb91-9844-4a10-84b1-3055c5643aa8",
    "title": "Asamblea 2",
    "description": "Reunión ordinaria",
    "date": "2024-11-18T15:00:00.000Z"
}
