### Health Check
GET http://localhost:3000/api/health

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "123123"
}

### Store auth token from login response
@authToken = {{login.response.body.access_token}}